#!/usr/bin/env python

import sys
import os
from pytube import YouTube
from pydub import AudioSegment


youtube_url = sys.argv[1]

print("Getting Metadata from Youtube")
yt = YouTube(youtube_url)

file_name = yt.title
file_ext = ".mp4"

print("Downloadling Video: " + file_name)
audio_mp4 = yt.streams.filter(only_audio=True).filter(file_extension='mp4').first()
file_name = audio_mp4.default_filename
audio_mp4.download()

print("Converting to mp3")
audio_file = AudioSegment.from_file(file_name, file_ext[1:])
audio_file.export(file_name[:-4] + ".mp3", format="mp3")
os.remove(file_name)

print("Done")

